name: Build and Deploy

on:
  push:
    branches: [ "feature/32_editar_perfil" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Create Firebase Credentials
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > src/main/resources/firebase-service-account.json
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: build/libs/
      - run: docker build -t my-backend .
      - run: |
          docker stop kot-backend || true
          docker rm kot-backend || true
          docker run -d --name kot-backend -p 8080:8080 my-backend